name: 'setup apt repositories'
description: "sets up package apt repositories for clang/gcc on ubuntu 24.02"
runs:
  using: "composite"
  steps:
    - name: Add repos
      shell: bash
      run: |
        source /etc/os-release
        
        # clang-19
        echo "deb http://apt.llvm.org/${UBUNTU_CODENAME}/ llvm-toolchain-${UBUNTU_CODENAME}-19 main" | sudo tee /etc/apt/sources.list.d/llvm-19.list
        curl https://apt.llvm.org/llvm-snapshot.gpg.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/llvm-19.gpg > /dev/null
        
        sudo apt-get update -y
