name: 'setup apt repositories'
description: "sets up package apt repositories for clang/gcc"
runs:
  using: "composite"
  steps:
    - name: Add repos
      shell: bash
      run: |
       # gcc-13
       sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
       
       # clang-16
       source /etc/os-release
       echo "deb http://apt.llvm.org/${UBUNTU_CODENAME}/ llvm-toolchain-${UBUNTU_CODENAME}-16 main" | sudo tee /etc/apt/sources.list.d/llvm-16.list
       curl https://apt.llvm.org/llvm-snapshot.gpg.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/llvm-16.gpg > /dev/null
