name: "setup macports"
description: "setup MacPorts on macOS"
runs:
  using: "composite"
  steps:
    - name: Cache MacPorts
      uses: actions/cache@v3
      id: cache-macports
      with:
        path: /opt/local/
        key: macports-v2.10.7-${{ runner.os }}-${{ inputs.compiler }}

    - name: Fix MacPorts permissions
      if: ${{ steps.cache-macports.outputs.cache-hit == 'true' }}
      shell: bash
      run: sudo chown -R root:wheel /opt/local

    - name: Install MacPorts
      if: ${{ steps.cache-macports.outputs.cache-hit != 'true' }}
      shell: bash
      run: |
        curl -LO https://github.com/macports/macports-base/releases/download/v2.10.7/MacPorts-2.10.7-15-Sequoia.pkg
        sudo installer -pkg MacPorts-2.10.7-15-Sequoia.pkg -target /

    - name: Add MacPorts to system paths
      shell: bash
      run: |
        # so sudo can find port
        echo "/opt/local/bin" | sudo tee -a /etc/paths
        echo "/opt/local/sbin" | sudo tee -a /etc/paths
        # also ensure it’s in the user path
        echo "/opt/local/bin" >> $GITHUB_PATH
        hash -r
