name: 'get conan dependency provider'
description: "installs conan_provider.cmake"
runs:
  using: "composite"
  steps:
      - name: Get dependency provider
        shell: bash
        run: |
          curl -L https://github.com/conan-io/cmake-conan/raw/develop2/conan_provider.cmake -o conan_provider.cmake
