name: Release

on:
  workflow_call:
    inputs:
      public_artifactory:
        type: boolean
        default: false
      os:
        required: true
        type: string
        default: ubuntu-22.04
      compiler:
        type: string
        default: clang-16
      cmake-version:
        type: string
        default: 3.21.7
      conan-version:
        type: string
        default: 1.60.1
      use-tag: # if true an existing tag/release is update; otherwise the job fails. If true the job will also fail if the tag doesn't match the version reported via conan.
        type: boolean
        default: false
    secrets:
      CONAN_USER:
        required: true
      CONAN_PW:
        required: true

jobs:
  publish-release:
    name: Creates a release for the current version defined in CMake and uploads a Conan package to conan.dice-research.org. Fails if release for the version exists already.
    defaults:
      run:
        shell: bash
    runs-on: ${{ inputs.os }}
    steps:
      - name: Fail fast if use-tag is used without a tag
        if: ${{ inputs.use-tag && github.ref_type != 'tag' }}
        run: exit 1
      # setup env
      - name: Ensure environment
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common curl

      - name: Add repos for for gcc-13 and clang-16
        run: |
          # gcc-13
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y

          # clang-16
          source /etc/os-release
          echo "deb http://apt.llvm.org/${UBUNTU_CODENAME}/ llvm-toolchain-${UBUNTU_CODENAME}-16 main" | sudo tee /etc/apt/sources.list.d/llvm-16.list
          curl https://apt.llvm.org/llvm-snapshot.gpg.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/llvm-16.gpg > /dev/null

      - name: Ensure stdlib version
        run: |
          sudo apt install libstdc++-13-dev -y
    
      - name: Get minimum cmake version
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: ${{ inputs.cmake-version }}
      - name: Install compiler
        id: install_cc
        uses: rlalik/setup-cpp-compiler@v1.2
        with:
          compiler: ${{ inputs.compiler }}
      - uses: rui314/setup-mold@v1
      - name: Install conan
        env:
          CC: ${{ steps.install_cc.outputs.cc }}
          CXX: ${{ steps.install_cc.outputs.cxx }}
        run: |
          pip3 install "conan==${{ inputs.conan-version }}"
          conan profile new --detect default
          conan profile update settings.compiler.libcxx=libstdc++11 default
          conan profile update env.CXXFLAGS="${CXXFLAGS}" default
          conan profile update env.CMAKE_EXE_LINKER_FLAGS="${CMAKE_EXE_LINKER_FLAGS}" default
          conan profile update env.CXX="${CXX}" default
          conan profile update env.CC="${CC}" default
          conan remote add dice-group https://conan.dice-research.org/artifactory/api/conan/tentris
          conan remote add tentris-private https://conan.dice-research.org/artifactory/api/conan/tentris-private
          conan user -p "${{ secrets.CONAN_PW }}" -r dice-group "${{ secrets.CONAN_USER }}"
          conan user -p "${{ secrets.CONAN_PW }}" -r tentris-private "${{ secrets.CONAN_USER }}"

      - name: Cache conan data
        id: cache-conan
        uses: actions/cache@v3
        with:
          path: ~/.conan/data
          key: ${{ env.os }}-${{ env.compiler }}-conan

      - name: Checkout
        uses: actions/checkout@v3

      - name: Extract asset version
        id: extract_asset_version
        run: |
          echo "asset_version=$(conan inspect . --raw version)" >> $GITHUB_ENV
      - name: Fail if use-tag and tag is not equal to package version from conan inspect
        if: ${{ inputs.use-tag &&  github.ref_name != format('v{0}', env.asset_version) }}
        run: exit 1
      
      - name: Create github release
        uses: ncipollo/release-action@v1
        with:
          tag: "v${{ env.asset_version }}"
          allowUpdates: ${{ inputs.use-tag }}

      - name: Set package name identifier
        run: |
          echo "conan_package_identifier=$(conan inspect . --raw name)/$(conan inspect . --raw version)@" >> $GITHUB_ENV

      - name: Create Package
        env:
          CC: ${{ steps.install_cc.outputs.cc }}
          CXX: ${{ steps.install_cc.outputs.cxx }}
        run: |
          (conan remove -f "${{ env.conan_package_identifier }}" || true)
          conan create . "${{ env.conan_package_identifier }}" --build missing -pr:b=default -pr:h=default

      - name: Select public artifactory for upload
        if: ${{ fromJSON(inputs.public_artifactory) }}
        run: |
          echo "remote_artifactory_name=dice-group" >> $GITHUB_ENV

      - name: Select private artifactory for upload
        if: ${{ !fromJSON(inputs.public_artifactory) }}
        run: |
          echo "remote_artifactory_name=tentris-private" >> $GITHUB_ENV

      - name: Upload to artifactory
        run: |
          conan upload "${{ env.conan_package_identifier }}" -r ${{ env.remote_artifactory_name }}
